services:
  - type: web
    name: hitesh-ai-backend
    env: docker
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: info 